/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDonationsRouteImport } from './routes/_authenticated/donations'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DocsPrivacyRouteImport } from './routes/docs/privacy'
import { Route as DocsTosRouteImport } from './routes/docs/tos'
import { Route as VideosSlugRouteImport } from './routes/videos.$slug'
import { Route as AuthenticatedDonationsIndexRouteImport } from './routes/_authenticated/donations.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiChatSplatRouteImport } from './routes/api/chat/$'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ChatOverlayTokenRouteImport } from './routes/chat.overlay.$token'
import { Route as ApiIntegrationDonationalertsCallbackRouteImport } from './routes/api/integration/donationalerts/callback'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDonationsRoute = AuthenticatedDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPrivacyRoute = DocsPrivacyRouteImport.update({
  id: '/docs/privacy',
  path: '/docs/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTosRoute = DocsTosRouteImport.update({
  id: '/docs/tos',
  path: '/docs/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/videos/$slug',
  path: '/videos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDonationsIndexRoute =
  AuthenticatedDonationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDonationsRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSplatRoute = ApiChatSplatRouteImport.update({
  id: '/api/chat/$',
  path: '/api/chat/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatOverlayTokenRoute = ChatOverlayTokenRouteImport.update({
  id: '/chat/overlay/$token',
  path: '/chat/overlay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationDonationalertsCallbackRoute =
  ApiIntegrationDonationalertsCallbackRouteImport.update({
    id: '/api/integration/donationalerts/callback',
    path: '/api/integration/donationalerts/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AuthenticatedIndexRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/donations': typeof AuthenticatedDonationsRouteWithChildren
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/api/health': typeof ApiHealthRoute
  '/docs/privacy': typeof DocsPrivacyRoute
  '/docs/tos': typeof DocsTosRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$': typeof ApiChatSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chat/overlay/$token': typeof ChatOverlayTokenRoute
  '/donations/': typeof AuthenticatedDonationsIndexRoute
  '/api/integration/donationalerts/callback': typeof ApiIntegrationDonationalertsCallbackRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/api/health': typeof ApiHealthRoute
  '/docs/privacy': typeof DocsPrivacyRoute
  '/docs/tos': typeof DocsTosRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$': typeof ApiChatSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chat/overlay/$token': typeof ChatOverlayTokenRoute
  '/donations': typeof AuthenticatedDonationsIndexRoute
  '/api/integration/donationalerts/callback': typeof ApiIntegrationDonationalertsCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/donations': typeof AuthenticatedDonationsRouteWithChildren
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/api/health': typeof ApiHealthRoute
  '/docs/privacy': typeof DocsPrivacyRoute
  '/docs/tos': typeof DocsTosRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/$': typeof ApiChatSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chat/overlay/$token': typeof ChatOverlayTokenRoute
  '/_authenticated/donations/': typeof AuthenticatedDonationsIndexRoute
  '/api/integration/donationalerts/callback': typeof ApiIntegrationDonationalertsCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/alerts'
    | '/chat'
    | '/donations'
    | '/integrations'
    | '/settings'
    | '/videos'
    | '/api/health'
    | '/docs/privacy'
    | '/docs/tos'
    | '/videos/$slug'
    | '/api/auth/$'
    | '/api/chat/$'
    | '/api/trpc/$'
    | '/chat/overlay/$token'
    | '/donations/'
    | '/api/integration/donationalerts/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/alerts'
    | '/chat'
    | '/integrations'
    | '/settings'
    | '/videos'
    | '/api/health'
    | '/docs/privacy'
    | '/docs/tos'
    | '/videos/$slug'
    | '/'
    | '/api/auth/$'
    | '/api/chat/$'
    | '/api/trpc/$'
    | '/chat/overlay/$token'
    | '/donations'
    | '/api/integration/donationalerts/callback'
  id:
    | '__root__'
    | '/$'
    | '/_authenticated'
    | '/_authenticated/alerts'
    | '/_authenticated/chat'
    | '/_authenticated/donations'
    | '/_authenticated/integrations'
    | '/_authenticated/settings'
    | '/_authenticated/videos'
    | '/api/health'
    | '/docs/privacy'
    | '/docs/tos'
    | '/videos/$slug'
    | '/_authenticated/'
    | '/api/auth/$'
    | '/api/chat/$'
    | '/api/trpc/$'
    | '/chat/overlay/$token'
    | '/_authenticated/donations/'
    | '/api/integration/donationalerts/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  DocsPrivacyRoute: typeof DocsPrivacyRoute
  DocsTosRoute: typeof DocsTosRoute
  VideosSlugRoute: typeof VideosSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatSplatRoute: typeof ApiChatSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ChatOverlayTokenRoute: typeof ChatOverlayTokenRoute
  ApiIntegrationDonationalertsCallbackRoute: typeof ApiIntegrationDonationalertsCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donations': {
      id: '/_authenticated/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof AuthenticatedDonationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/privacy': {
      id: '/docs/privacy'
      path: '/docs/privacy'
      fullPath: '/docs/privacy'
      preLoaderRoute: typeof DocsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/tos': {
      id: '/docs/tos'
      path: '/docs/tos'
      fullPath: '/docs/tos'
      preLoaderRoute: typeof DocsTosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/videos/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/donations/': {
      id: '/_authenticated/donations/'
      path: '/'
      fullPath: '/donations/'
      preLoaderRoute: typeof AuthenticatedDonationsIndexRouteImport
      parentRoute: typeof AuthenticatedDonationsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/$': {
      id: '/api/chat/$'
      path: '/api/chat/$'
      fullPath: '/api/chat/$'
      preLoaderRoute: typeof ApiChatSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/overlay/$token': {
      id: '/chat/overlay/$token'
      path: '/chat/overlay/$token'
      fullPath: '/chat/overlay/$token'
      preLoaderRoute: typeof ChatOverlayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integration/donationalerts/callback': {
      id: '/api/integration/donationalerts/callback'
      path: '/api/integration/donationalerts/callback'
      fullPath: '/api/integration/donationalerts/callback'
      preLoaderRoute: typeof ApiIntegrationDonationalertsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDonationsRouteChildren {
  AuthenticatedDonationsIndexRoute: typeof AuthenticatedDonationsIndexRoute
}

const AuthenticatedDonationsRouteChildren: AuthenticatedDonationsRouteChildren =
  {
    AuthenticatedDonationsIndexRoute: AuthenticatedDonationsIndexRoute,
  }

const AuthenticatedDonationsRouteWithChildren =
  AuthenticatedDonationsRoute._addFileChildren(
    AuthenticatedDonationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDonationsRoute: typeof AuthenticatedDonationsRouteWithChildren
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDonationsRoute: AuthenticatedDonationsRouteWithChildren,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  DocsPrivacyRoute: DocsPrivacyRoute,
  DocsTosRoute: DocsTosRoute,
  VideosSlugRoute: VideosSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatSplatRoute: ApiChatSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ChatOverlayTokenRoute: ChatOverlayTokenRoute,
  ApiIntegrationDonationalertsCallbackRoute:
    ApiIntegrationDonationalertsCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
