/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedDonationsRouteImport } from './routes/_authenticated/donations'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ShareSlugRouteImport } from './routes/share.$slug'
import { Route as AuthenticatedDonationsIndexRouteImport } from './routes/_authenticated/donations.index'
import { Route as AuthenticatedDonationsVideosRouteImport } from './routes/_authenticated/donations.videos'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiIntegrationDonationalertsCallbackRouteImport } from './routes/api/integration/donationalerts/callback'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDonationsRoute = AuthenticatedDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDonationsIndexRoute =
  AuthenticatedDonationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDonationsRoute,
  } as any)
const AuthenticatedDonationsVideosRoute =
  AuthenticatedDonationsVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedDonationsRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationDonationalertsCallbackRoute =
  ApiIntegrationDonationalertsCallbackRouteImport.update({
    id: '/api/integration/donationalerts/callback',
    path: '/api/integration/donationalerts/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/donations': typeof AuthenticatedDonationsRouteWithChildren
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/share/$slug': typeof ShareSlugRoute
  '/donations/videos': typeof AuthenticatedDonationsVideosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/donations/': typeof AuthenticatedDonationsIndexRoute
  '/api/integration/donationalerts/callback': typeof ApiIntegrationDonationalertsCallbackRoute
}
export interface FileRoutesByTo {
  '/alerts': typeof AuthenticatedAlertsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/share/$slug': typeof ShareSlugRoute
  '/': typeof AuthenticatedIndexRoute
  '/donations/videos': typeof AuthenticatedDonationsVideosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/donations': typeof AuthenticatedDonationsIndexRoute
  '/api/integration/donationalerts/callback': typeof ApiIntegrationDonationalertsCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/donations': typeof AuthenticatedDonationsRouteWithChildren
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/share/$slug': typeof ShareSlugRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/donations/videos': typeof AuthenticatedDonationsVideosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/donations/': typeof AuthenticatedDonationsIndexRoute
  '/api/integration/donationalerts/callback': typeof ApiIntegrationDonationalertsCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/donations'
    | '/integrations'
    | '/settings'
    | '/api/health'
    | '/share/$slug'
    | '/donations/videos'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/donations/'
    | '/api/integration/donationalerts/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alerts'
    | '/integrations'
    | '/settings'
    | '/api/health'
    | '/share/$slug'
    | '/'
    | '/donations/videos'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/donations'
    | '/api/integration/donationalerts/callback'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/alerts'
    | '/_authenticated/donations'
    | '/_authenticated/integrations'
    | '/_authenticated/settings'
    | '/api/health'
    | '/share/$slug'
    | '/_authenticated/'
    | '/_authenticated/donations/videos'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authenticated/donations/'
    | '/api/integration/donationalerts/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ShareSlugRoute: typeof ShareSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiIntegrationDonationalertsCallbackRoute: typeof ApiIntegrationDonationalertsCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donations': {
      id: '/_authenticated/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof AuthenticatedDonationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/donations/': {
      id: '/_authenticated/donations/'
      path: '/'
      fullPath: '/donations/'
      preLoaderRoute: typeof AuthenticatedDonationsIndexRouteImport
      parentRoute: typeof AuthenticatedDonationsRoute
    }
    '/_authenticated/donations/videos': {
      id: '/_authenticated/donations/videos'
      path: '/videos'
      fullPath: '/donations/videos'
      preLoaderRoute: typeof AuthenticatedDonationsVideosRouteImport
      parentRoute: typeof AuthenticatedDonationsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integration/donationalerts/callback': {
      id: '/api/integration/donationalerts/callback'
      path: '/api/integration/donationalerts/callback'
      fullPath: '/api/integration/donationalerts/callback'
      preLoaderRoute: typeof ApiIntegrationDonationalertsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDonationsRouteChildren {
  AuthenticatedDonationsVideosRoute: typeof AuthenticatedDonationsVideosRoute
  AuthenticatedDonationsIndexRoute: typeof AuthenticatedDonationsIndexRoute
}

const AuthenticatedDonationsRouteChildren: AuthenticatedDonationsRouteChildren =
  {
    AuthenticatedDonationsVideosRoute: AuthenticatedDonationsVideosRoute,
    AuthenticatedDonationsIndexRoute: AuthenticatedDonationsIndexRoute,
  }

const AuthenticatedDonationsRouteWithChildren =
  AuthenticatedDonationsRoute._addFileChildren(
    AuthenticatedDonationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedDonationsRoute: typeof AuthenticatedDonationsRouteWithChildren
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedDonationsRoute: AuthenticatedDonationsRouteWithChildren,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ShareSlugRoute: ShareSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiIntegrationDonationalertsCallbackRoute:
    ApiIntegrationDonationalertsCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
