import * as icons from "lucide-react";

export type IconComponent = icons.LucideIcon;

export const Icons = {
  addVideo: icons.ListPlus,
  alerts: icons.Bell,
  bookmark: icons.Bookmark,
  cancel: icons.X,
  checked: icons.Check,
  chevronDown: icons.ChevronDown,
  chevronLeft: icons.ChevronLeft,
  chevronRight: icons.ChevronRight,
  copied: icons.Check,
  copy: icons.Copy,
  dashboard: icons.LayoutDashboard,
  dateRange: icons.ChevronDown,
  donations: icons.Sparkles,
  edit: icons.Pencil,
  externalLink: icons.ExternalLink,
  filter: icons.SlidersHorizontal,
  greetingAccent: icons.Sparkles,
  help: icons.CircleHelp,
  integrations: icons.Plug,
  list: icons.List,
  loader: icons.LoaderCircle,
  logout: icons.LogOut,
  moon: icons.Moon,
  manualVideo: icons.UserRoundPlus,
  notWatched: icons.Circle,
  platform: icons.Share2,
  retry: icons.RotateCcw,
  search: icons.Search,
  secure: icons.ShieldCheck,
  settings: icons.Settings,
  submit: icons.Check,
  sun: icons.Sun,
  video: icons.Video,
  videoFromDonation: icons.Sparkles,
  wallet: icons.Wallet,
  warn: icons.TriangleAlert,
  watched: icons.CheckCircle2,
};
