import * as icons from "lucide-react";

export const Icons = {
  alerts: icons.Bell,
  bookmark: icons.Bookmark,
  cancel: icons.X,
  checked: icons.Check,
  chevronDown: icons.ChevronDown,
  chevronRight: icons.ChevronRight,
  copied: icons.Check,
  copy: icons.Copy,
  dashboard: icons.LayoutDashboard,
  dateRange: icons.ChevronRight,
  donations: icons.Sparkles,
  edit: icons.Pencil,
  filter: icons.SlidersHorizontal,
  integrations: icons.Plug,
  list: icons.List,
  loader: icons.LoaderCircle,
  logout: icons.LogOut,
  moon: icons.Moon,
  notWatched: icons.Circle,
  platform: icons.Share2,
  retry: icons.RotateCcw,
  search: icons.Search,
  secure: icons.ShieldCheck,
  settings: icons.Settings,
  submit: icons.Check,
  sun: icons.Sun,
  video: icons.Video,
  wallet: icons.Wallet,
  warn: icons.TriangleAlert,
  watched: icons.CheckCircle2,
};
